config/routes.rb
TomAndJensWedding::Application.routes.draw do
  resources :attendings


  get "static_pages/index"

  get "static_pages/venue"

  get "static_pages/getting_there"

  get "static_pages/barcelona"
get "static_pages/gift"
  resources :menus


  resources :rsvps


  authenticated :user do
    root :to => 'static_pages#index'
  end
  root :to => "static_pages#index"
  devise_for :users
  resources :users
  
  match '/contact-us', to: 'contact_us#contacts#new'
  match '/home', to: 'static_pages#index'
  match '/rsvp', to: 'attendings#new'
  match '/venue', to: 'static_pages#venue'
  match '/gettingthere', to: 'static_pages#getting_there'
  match '/barcelona', to: 'static_pages#barcelona'
   match '/gift', to: 'static_pages#gift'
end

app/models/attending.rb
class Attending < ActiveRecord::Base
  attr_accessible :attending, :attending1, :attending2, :attending3, :name, :name1, :name2, :name3
  
  belongs_to :user
end

app/controllers/attendings_controller.rb
class AttendingsController < ApplicationController

  # GET /attendings
  # GET /attendings.json
  def index
    @attendings = Attending.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendings }
    end
  end

  # GET /attendings/1
  # GET /attendings/1.json
  def show
 if signed_in?
  @has_made_rsvp = current_user.attendings(:name).present?
    @attending = Attending.find(params[:id])
  
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attending }
    end
	 end
  end

  # GET /attendings/new
  # GET /attendings/new.json
  def new
   
	@attending = Attending.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attending }
   
  end
end
  # GET /attendings/1/edit
  def edit
    @attending = Attending.find(params[:id])
  end

  # POST /attendings
  # POST /attendings.json
  def create
    
   
	@attending = current_user.attendings.build(params[:attending])

    respond_to do |format|
      if @attending.save
	   
        format.html { redirect_to @attending, notice: 'Your RSVP was successfully created.' }
        format.json { render json: @attending, status: :created, location: @attending }
      else
        format.html { render action: "new" }
        format.json { render json: @attending.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendings/1
  # PUT /attendings/1.json
  def update
    @attending = Attending.find(params[:id])

    respond_to do |format|
      if @attending.update_attributes(params[:attending])
        format.html { redirect_to @attending, notice: 'Your RSVP was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attending.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendings/1
  # DELETE /attendings/1.json
  def destroy
    @attending = Attending.find(params[:id])
    @attending.destroy

    respond_to do |format|
      format.html { redirect_to attendings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attendings_helper.rb
module AttendingsHelper
end

app/views/attendings/_form.html.erb
<%= simple_form_for(@attending) do |f| %>
 
<div class="g-form-group">
										<div class="g-form-group-rows">
											<div class="g-form-row" id="name_row">
												<div class="g-form-row-label">
													<%= f.label :name, 'Name', :class => 'g-form-row-label-h' %> 
												</div>
												<div class="g-form-row-field">
													<%= f.text_field :name, :value => current_user.name %>
												</div>
												<div class="g-form-row-state" id="name_state"></div>
											
												<div class="g-form-row-label">
												<%= f.label :Attending, 'Attending', :class => 'g-form-row-label-h' %> 
												</div>
												<div class="g-form-row-field">
											<%= f.radio_button(:attending, "Yes") %>
                                           <%= f.label(:attending, "Yes") %>
	                                       <%= f.radio_button(:attending, "No") %>
                                            <%= f.label(:attending, "No") %>
											</div>
											</div>
											
											<div class="g-form-row" id="name_row">
												<div class="g-form-row-label">
													 <%= f.label :name1, "Name of guest" %>
												</div>
												<div class="g-form-row-field">
													<%= f.text_field :name1 %>
												</div>
												<div class="g-form-row-state" id="name_state"></div>
											<div class="g-form-row-label">
												<%= f.label :Attending1, 'Attending', :class => 'g-form-row-label-h' %> 
												</div>
												<div class="g-form-row-field">
											<%= f.radio_button(:attending1, "Yes") %>
                                           <%= f.label(:attending1, "Yes") %>
	                                       <%= f.radio_button(:attending1, "No") %>
                                            <%= f.label(:attending1, "No") %>
											</div>
											</div>
											<div class="g-form-row" id="name_row">
												<div class="g-form-row-label">
												<%= f.label :name2, "Name of guest" %>
												</div>
												<div class="g-form-row-field">
												<%= f.text_field :name2 %>
												</div>
												<div class="g-form-row-state" id="name_state"></div>
											<div class="g-form-row-label">
												<%= f.label :Attending2, 'Attending', :class => 'g-form-row-label-h' %> 
												</div>
												<div class="g-form-row-field">
											<%= f.radio_button(:attending2, "Yes") %>
                                           <%= f.label(:attending2, "Yes") %>
	                                       <%= f.radio_button(:attending2, "No") %>
                                            <%= f.label(:attending2, "No") %>
											</div>
											</div>
											<div class="g-form-row" id="name_row">
												<div class="g-form-row-label">
														<%= f.label :name3, "Name of guest" %>
												</div>
												<div class="g-form-row-field">
													<%= f.text_field :name3 %>
												</div>
												<div class="g-form-row-state" id="name_state"></div>
											<div class="g-form-row-label">
												<%= f.label :Attending, 'Attending', :class => 'g-form-row-label-h' %> 
												</div>
												<div class="g-form-row-field">
											<%= f.radio_button(:attending3, "Yes") %>
                                           <%= f.label(:attending3, "Yes") %>
	                                       <%= f.radio_button(:attending3, "No") %>
                                            <%= f.label(:attending3, "No") %>
											</div>
											</div>
											<div class="g-form-row">
												<div class="g-form-row-label"></div>
												 <div class="form-actions">
												 <%= f.button :submit, 'RSVP' %>
												 </div>
												 <% end %>
											</div>
										</div>

app/views/attendings/edit.html.erb
				<div class="l-submain type_fullwidth">
					<div class="l-submain-h g-html i-cf">
					
						<div class="w-map">
							<div class="w-map-h" style="height: 300px;">
							<%= image_tag("portvell.jpg", :class=>"w-map-h", :style=>"300px;") %>
							</div>
						</div>
						
					</div>
				</div>
				
				<div class="l-submain">
					<div class="l-submain-h g-html i-cf">
					<p id="notice"><%= notice %></p>
						<div class="g-cols">
							<div class="one-third">
							
								<h3>Contact Info</h3>
								
								<div class="w-contacts">
									<div class="w-contacts-h">
										<div class="w-contacts-list">
											<div class="w-contacts-item for_address">
												<i class="icon-location"></i>
												<span class="w-contacts-item-name">Questions </span>
												<span class="w-contacts-item-value">: If you have any questions or problems or want to clarify anything dont hesitate to call me or Jen, or if your at work then email ;) </span>
											</div>
											<div class="w-contacts-item for_phone">
												<i class="icon-mobile"></i>
												<span class="w-contacts-item-name">Phone:</span>
												<span class="w-contacts-item-value">+44 7976884486</span>
											</div>
											<div class="w-contacts-item for_email">
												<i class="icon-mail"></i>
												<span class="w-contacts-item-name">Email:</span>
												<span class="w-contacts-item-value"><a href="mailto:tmurdoch_99@yahoo.com">tmurdoch_99@yahoo.com</a></span>
											</div>
										</div>
									</div>
								</div>

								<div class="g-hr">
									<span class="g-hr-h">
										<i class="icon-star"></i>
									</span>
								</div>
								
								
								
								
							</div>
							<div class="two-thirds">
							
								<h3>Editing RSVP</h3>
								
							
<%= render 'form' %>


	
								
								</div>
  
							</div>
						</div>
						
					</div>
				</div>
				
			</div>
		</div>
		<!-- /MAIN -->

app/views/attendings/index.html.erb
<div class="l-submain">
					<div class="l-submain-h g-html">

<h1>Listing RSVPs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Attending</th>
    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendings.each do |attending| %>
  <tr>
   <tr> <td><%= attending.name %></td>
    <td><%= attending.attending %></td></tr>
   <tr><td><%= attending.name1 %></td>
    <td><%= attending.attending1 %></td></tr>
   <tr> <td><%= attending.name2 %></td>
    <td><%= attending.attending2 %></td></tr>
    <tr><td><%= attending.name3 %></td>
    <td><%= attending.attending3 %></td></tr>
    <tr><td><%= link_to 'Show', attending %></td>
    <td><%= link_to 'Edit', edit_attending_path(attending) %></td>
    <td><%= link_to 'Destroy', attending, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attending', new_attending_path %>

app/views/attendings/new.html.erb
				<div class="l-submain type_fullwidth">
					<div class="l-submain-h g-html i-cf">
					
						<div class="w-map">
							<div class="w-map-h" style="height: 300px;">
							<%= image_tag("portvell.jpg", :class=>"w-map-h", :style=>"300px;") %>
							</div>
						</div>
						
					</div>
				</div>
				
				<div class="l-submain">
					<div class="l-submain-h g-html i-cf">
					<p id="notice"><%= notice %></p>
						<div class="g-cols">
							<div class="one-third">
							
								<h3>Contact Info</h3>
								
								<div class="w-contacts">
									<div class="w-contacts-h">
										<div class="w-contacts-list">
											<div class="w-contacts-item for_address">
												<i class="icon-location"></i>
												<span class="w-contacts-item-name">Questions</span>
												<span class="w-contacts-item-value">: If you have any questions or problems or want to clarify anything don't hesitate to call me or Jen, or if you're at work then email ;) </span>
											</div>
											<div class="w-contacts-item for_phone">
												<i class="icon-mobile"></i>
												<span class="w-contacts-item-name">Phone:</span>
												<span class="w-contacts-item-value">+44 7976884486</span>
											</div>
											<div class="w-contacts-item for_email">
												<i class="icon-mail"></i>
												<span class="w-contacts-item-name">Email:</span>
												<span class="w-contacts-item-value"><a href="mailto:tmurdoch_99@yahoo.com">tmurdoch_99@yahoo.com</a></span>
											</div>
										</div>
									</div>
								</div>

								<div class="g-hr">
									<span class="g-hr-h">
										<i class="icon-star"></i>
									</span>
								</div>
								
								
								
								
							</div>
							<div class="two-thirds">
							
								<h3>RSVP</h3>
						
 
							
 
 <%= render 'form' %>


</div>	
 </div>	
</div>
</div>
</div>

app/views/attendings/show.html.erb
				<div class="l-submain type_fullwidth">
					<div class="l-submain-h g-html i-cf">
					
						<div class="w-map">
							<div class="w-map-h" style="height: 300px;">
							<%= image_tag("portvell.jpg", :class=>"w-map-h", :style=>"300px;") %>
							</div>
						</div>
						
					</div>
				</div>
				
				<div class="l-submain">
					<div class="l-submain-h g-html i-cf">
					<p id="notice"><%= notice %></p>
						<div class="g-cols">
							<div class="one-third">
							
								<h3>Contact Info</h3>
								
								<div class="w-contacts">
									<div class="w-contacts-h">
										<div class="w-contacts-list">
											<div class="w-contacts-item for_address">
												<i class="icon-location"></i>
												<span class="w-contacts-item-name">Questions: </span>
												<span class="w-contacts-item-value"> If you have any questions or problems or want to clarify anything dont hesitate to call me or Jen, or if your at work then email ;) </span>
											</div>
											<div class="w-contacts-item for_phone">
												<i class="icon-mobile"></i>
												<span class="w-contacts-item-name">Phone:</span>
												<span class="w-contacts-item-value">+44 7976884486</span>
											</div>
											<div class="w-contacts-item for_email">
												<i class="icon-mail"></i>
												<span class="w-contacts-item-name">Email:</span>
												<span class="w-contacts-item-value"><a href="mailto:tmurdoch_99@yahoo.com">tmurdoch_99@yahoo.com</a></span>
											</div>
										</div>
									</div>
								</div>

								<div class="g-hr">
									<span class="g-hr-h">
										<i class="icon-star"></i>
									</span>
								</div>
								
								
								
								
							</div>
							<div class="two-thirds">
							
								<h3>RSVP</h3>
						

<p><%= @attending.name %> <% if @attending.attending == 'Yes' %>is attending. <% else %><% if @attending.attending == 'No' %>is not attending :(<% end %><% end %> </p>
<p><% if @attending.name1 =="" %> <% else %> <%= @attending.name1 %> <% if @attending.attending1 == 'Yes' %>is attending. <% else %>is not attending :(<% end %><% end %> </p>
<p><% if @attending.name2 =="" %> <% else %> <%= @attending.name2 %> <% if @attending.attending2 == 'Yes' %>is attending. <% else %>is not attending :(<% end %><% end %> </p>
<p><% if @attending.name3 or @attending.attending3  =="" %> <% else %> <%= @attending.name3 %> <% if @attending.attending3 == 'Yes' %>is attending. <% else %>is not attending :(<% end %><% end %>  </p>
					
							<%= link_to 'Edit', edit_attending_path(@attending) %> 
 


</div>
</div>
 
</div>
</div>
</div>