config/routes.rb
TomAndJensWedding::Application.routes.draw do
  resources :attendings


  get "static_pages/index"

  get "static_pages/venue"

  get "static_pages/getting_there"

  get "static_pages/barcelona"
get "static_pages/gift"
  resources :menus


  resources :rsvps


  authenticated :user do
    root :to => 'static_pages#index'
  end
  root :to => "static_pages#index"
  devise_for :users
  resources :users
  
  match '/contact-us', to: 'contact_us#contacts#new'
  match '/home', to: 'static_pages#index'
  match '/rsvp', to: 'attendings#new'
  match '/venue', to: 'static_pages#venue'
  match '/gettingthere', to: 'static_pages#getting_there'
  match '/barcelona', to: 'static_pages#barcelona'
   match '/gift', to: 'static_pages#gift'
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  attr_accessible :attending1, :attending2, :attending3, :attending4, :name1, :name2, :name3, :name4
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  # GET /rsvps
  # GET /rsvps.json
  def index
    @rsvps = Rsvp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rsvps }
    end
  end

  # GET /rsvps/1
  # GET /rsvps/1.json
  def show
    @rsvp = Rsvp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rsvp }
    end
  end

  # GET /rsvps/new
  # GET /rsvps/new.json
  def new
    @rsvp = Rsvp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rsvp }
    end
  end

  # GET /rsvps/1/edit
  def edit
    @rsvp = Rsvp.find(params[:id])
  end

  # POST /rsvps
  # POST /rsvps.json
  def create
    @rsvp = Rsvp.new(params[:rsvp])

    respond_to do |format|
      if @rsvp.save
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully created.' }
        format.json { render json: @rsvp, status: :created, location: @rsvp }
      else
        format.html { render action: "new" }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rsvps/1
  # PUT /rsvps/1.json
  def update
    @rsvp = Rsvp.find(params[:id])

    respond_to do |format|
      if @rsvp.update_attributes(params[:rsvp])
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.json
  def destroy
    @rsvp = Rsvp.find(params[:id])
    @rsvp.destroy

    respond_to do |format|
      format.html { redirect_to rsvps_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/rsvps/_form.html.erb
<form class="g-form"  id="contact_form">
<%= simple_form_for(@rsvp) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs ">
    
	<%= f.label :name1, "Name" %>
    <%= f.text_field :name1, :placeholder => current_user.name %>
	<div>
	<div class="form-inputs form-inline ">
    <%= f.label :name1, "Are you attending?" %>
	<%= f.radio_button(:attending1, "Yes") %>
      <%= f.label(:attending1, "Yes") %>
	  <%= f.radio_button(:attending1, "No") %>
      <%= f.label(:attending1, "No") %>
    </div>
    

   Add another guest <input type="radio" onclick="javascript:yesnoCheck();" name="yesno" id="yesCheck"><br>
   <div id="ifYes" style="display:none">
    <%= f.label :name2, "Name of guest" %>
    <%= f.text_field :name2 %>
   
	
	<div class="form-inputs form-inline ">
	 <%= f.label :name1, "Are they attending?" %>
	<%= f.radio_button(:attending2, "Yes") %>
      <%= f.label(:attending2, "Yes") %>
	  <%= f.radio_button(:attending2, "No") %>
      <%= f.label(:attending2, "No") %>
    </div>
</div>
   
	<%= f.label :name2, "Name of guest" %>
    <%= f.text_field :name2 %>
   
	
	<div class="form-inputs form-inline ">
	 <%= f.label :name1, "Are they attending?" %>
	<%= f.radio_button(:attending2, "Yes") %>
      <%= f.label(:attending2, "Yes") %>
	  <%= f.radio_button(:attending2, "No") %>
      <%= f.label(:attending2, "No") %>
    </div>
	
	<%= f.label :name3, "Name of guest" %>
    <%= f.text_field :name3 %>
   
   
   <div class="form-inputs form-inline ">
    <%= f.label :name1, "Are they attending?" %>
	<%= f.radio_button(:attending3, "Yes") %>
      <%= f.label(:attending3, "Yes") %>
	  <%= f.radio_button(:attending3, "No") %>
      <%= f.label(:attending3, "No") %>
     </div>
	<%= f.label :name4, "Name of guest" %>
    <%= f.text_field :name4 %>

	
	<div class="form-inputs form-inline ">
	 <%= f.label :name1, "Are they attending?" %>
	<%= f.radio_button(:attending3, "Yes") %>
      <%= f.label(:attending3, "Yes") %>
	  <%= f.radio_button(:attending3, "No") %>
      <%= f.label(:attending3, "No") %>
  </div>
</div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rsvps/edit.html.erb
<h1>Editing rsvp</h1>

<%= render 'form' %>

<%= link_to 'Show', @rsvp %> |
<%= link_to 'Back', rsvps_path %>

app/views/rsvps/index.html.erb
<h1>Listing rsvps</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Attending</th>
    <th>Name of guest</th>
    <th>Attending</th>
    <th>Name of guest</th>
    <th>Attending</th>
    <th>Name of guest</th>
    <th>Attending</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rsvps.each do |rsvp| %>
  <tr>
    <td><%= rsvp.name1 %></td>
    <td><%= rsvp.attending1 %></td>
    <td><%= rsvp.name2 %></td>
    <td><%= rsvp.attending2 %></td>
    <td><%= rsvp.name3 %></td>
    <td><%= rsvp.attending3 %></td>
    <td><%= rsvp.name4 %></td>
    <td><%= rsvp.attending4 %></td>
    <td><%= link_to 'Show', rsvp %></td>
    <td><%= link_to 'Edit', edit_rsvp_path(rsvp) %></td>
    <td><%= link_to 'Destroy', rsvp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rsvp', new_rsvp_path %>

app/views/rsvps/new.html.erb
				<div class="l-submain type_fullwidth">
					<div class="l-submain-h g-html i-cf">
					
						<div class="w-map">
							<div class="w-map-h" style="height: 300px;">
							<%= image_tag("portvell.jpg", :class=>"w-map-h", :style=>"300px;") %>
							</div>
						</div>
						
					</div>
				</div>
				
				<div class="l-submain">
					<div class="l-submain-h g-html i-cf">
					<p id="notice"><%= notice %></p>
						<div class="g-cols">
							<div class="one-third">
							
								<h3>Contact Info</h3>
								
								<div class="w-contacts">
									<div class="w-contacts-h">
										<div class="w-contacts-list">
											<div class="w-contacts-item for_address">
												<i class="icon-location"></i>
												<span class="w-contacts-item-name">Questions: </span>
												<span class="w-contacts-item-value"> If you have any questions or problems or want to clarify anything dont hesitate to call me or Jen, or if your at work then email ;) </span>
											</div>
											<div class="w-contacts-item for_phone">
												<i class="icon-mobile"></i>
												<span class="w-contacts-item-name">Phone:</span>
												<span class="w-contacts-item-value">+44 7976884486</span>
											</div>
											<div class="w-contacts-item for_email">
												<i class="icon-mail"></i>
												<span class="w-contacts-item-name">Email:</span>
												<span class="w-contacts-item-value"><a href="mailto:tmurdoch_99@yahoo.com">tmurdoch_99@yahoo.com</a></span>
											</div>
										</div>
									</div>
								</div>

								<div class="g-hr">
									<span class="g-hr-h">
										<i class="icon-star"></i>
									</span>
								</div>
								
								
								
								
							</div>
							<div class="two-thirds">
							
								<h3>RSVP</h3>
								<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
							<form class="g-form"  id="contact_form">
<%= simple_form_for(@rsvp) do |f| %>
  <%= f.error_notification %>
								<form class="g-form"  id="contact_form">
									<div class="g-alert type_success with_close" id="contact_form_success_message" style="opacity: 0; display: none;">
										<div class="g-alert-close"> &#10005; </div>
										<div class="g-alert-body">
											<p><b>Thank You!</b> Your message was sent.</p>
										</div>
									</div>
									<div class="g-alert type_error with_close" id="contact_form_error_message" style="opacity: 0; display: none;">
										<div class="g-alert-close"> &#10005; </div>
										<div class="g-alert-body">
											<p></p>
										</div>
									</div>
									<div class="g-form-group">
										<div class="g-form-group-rows">
											<div class="g-form-row" id="name_row">
												<div class="g-form-row-label">
													<%= f.label :name1, 'Name', :class => 'g-form-row-label-h' %> 
												</div>
												<div class="g-form-row-field">
													<%= f.text_field :name1, :placeholder => current_user.name %>
												</div>
												<div class="g-form-row-state" id="name_state"></div>
											</div>
											<div class="g-form-row" id="name_row">
												<div class="g-form-row-label">
													 <%= f.label :name2, "Name of guest" %>
												</div>
												<div class="g-form-row-field">
													<%= f.text_field :name2 %>
												</div>
												<div class="g-form-row-state" id="name_state"></div>
											</div>
											<div class="g-form-row" id="name_row">
												<div class="g-form-row-label">
												<%= f.label :name3, "Name of guest" %>
												</div>
												<div class="g-form-row-field">
												<%= f.text_field :name3 %>
												</div>
												<div class="g-form-row-state" id="name_state"></div>
											</div>
											<div class="g-form-row" id="name_row">
												<div class="g-form-row-label">
														<%= f.label :name4, "Name of guest" %>
												</div>
												<div class="g-form-row-field">
													<%= f.text_field :name4 %>
												</div>
												<div class="g-form-row-state" id="name_state"></div>
											</div>
											<div class="g-form-row">
												<div class="g-form-row-label"></div>
												 <div class="form-actions">
												 <%= f.button :submit %>
												 </div>
												 <% end %>
											</div>
										</div>
									</div>
								</form>
								
								</div>
  
							</div>
						</div>
						
					</div>
				</div>
				
			</div>
		</div>
		<!-- /MAIN -->

app/views/rsvps/show.html.erb
<h3 style="text-align: center;">Data Table</h3>
						<div class="g-hr type_invisible"></div>
						
<p id="notice"><%= notice %></p>



						<!-- Table -->
						<table class="g-table">
							<thead>
								<tr>
                                    <th>Name</th>
									<th>attending</th>
									
								</tr>
							</thead>
                            <tbody>
								<tr>
									<td><%= @attending.name %></td>
									<td><%=@attending.attending1 %></td>
									
								</tr>
								<tr>
									<td><%= @attending.name1 %></td>
									<td><%= @attending.attending1 %></td>
									
								</tr>
								<tr>
									<td><%= @attending.name2 %></td>
									<td><%=@attending.attending2 %></td>
									
								</tr>
								<tr>
									<td><%= @attending.name3 %></td>
									<td><%= @attending.attending3 %></td>
									
								</tr>
								<%= link_to 'Edit', edit_rsvp_path(@rsvp) %> |
                            <%= link_to 'Back', rsvps_path %>
							</tbody>
							</table>
</div>
</div>